<a href="https://colab.research.google.com/github/nigowda/DAV-1/blob/main/Numpy_01_ClassNotes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a = [1, 2, 4, "Adam", True]
a

[1, 2, 4, 'Adam', True]

In [ ]:
a = [1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [ ]:
res = []
for ele in a:
    res.append(ele**2)

print(res)

[1, 4, 9, 16, 25]


In [ ]:
res = [ele**2 for ele in a]
print(res)

[1, 4, 9, 16, 25]


In [ ]:
import numpy as np

In [ ]:
arr = np.array(a)
arr

array([1, 2, 3, 4, 5])

In [ ]:
type(a)

list

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr**2

array([ 1,  4,  9, 16, 25])

In [ ]:
lst = range(100000)

In [ ]:
%timeit [ele**2 for ele in lst]

32.7 ms ± 565 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
arr = np.array(lst)

In [ ]:
%timeit arr**2

64.2 µs ± 724 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
arr = np.array(range(1, 11))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr.ndim

1

In [ ]:
arr.shape

(10,)

In [ ]:
lst2d = [[1,2,3], [4,5,6], [10,11,12]]
lst2d

[[1, 2, 3], [4, 5, 6], [10, 11, 12]]

In [ ]:
arr2 = np.array(lst2d)
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12]])

In [ ]:
arr2.ndim

2

In [ ]:
arr2.shape

(3, 3)

In [ ]:
# range()

# np.arange(start, end, step)

In [ ]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
arr = np.arange(1, 5, 0.5)
arr

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.dtype

dtype('float64')

In [ ]:
arr = np.arange(5)
arr[2:4] = 0

print(arr)

[0 1 0 0 4]


In [ ]:
arr

array([0, 1, 0, 0, 4])

In [ ]:
a = np.array([1,2,3,4.0])
a

array([1., 2., 3., 4.])

In [ ]:
a.dtype

dtype('float64')

In [ ]:
a = np.array([1,2,3,4.9], dtype='int')
a

array([1, 2, 3, 4])

In [ ]:
np.array([1, 2, 3.14, 4, "harry"])

array(['1', '2', '3.14', '4', 'harry'], dtype='<U32')

In [ ]:
np.array([1, 2, 3.14, 4, "harry"], dtype='int')

ValueError: ignored

In [ ]:
arr

array([0, 1, 0, 0, 4])

In [ ]:
arr.astype('float')

array([0., 1., 0., 0., 4.])

# Indexing and Slicing

In [ ]:
m1 = np.arange(12)

In [ ]:
m1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
m1[0]

0

In [ ]:
m1[6]

6

In [ ]:
m1[-1]

11

In [ ]:
m1 = np.array([100,200,300,400,500,600])
m1

array([100, 200, 300, 400, 500, 600])

In [ ]:
m1[3]

400

In [ ]:
# multiple elements are extracted.
m1[[2, 3, 1]]

array([300, 400, 200])

In [ ]:
m1[[4,0,1,4,1,5]]

array([500, 100, 200, 500, 200, 600])

In [ ]:
m1[2, 3, 0, -1]

IndexError: ignored

In [ ]:
m1

array([100, 200, 300, 400, 500, 600])

In [ ]:
m1[:4]

array([100, 200, 300, 400])

In [ ]:
m1[-5:-1]

array([200, 300, 400, 500])

In [ ]:
m1[-1:1:-1]

array([600, 500, 400, 300])

In [ ]:
m1[-1:1]

array([], dtype=int64)

In [ ]:
a = np.array([0,1,2,3,4,5])
a[4:] = 10
print(a)

[ 0  1  2  3 10 10]


## Boolean Indexing
## Fancy Indexing

In [ ]:
m1 = np.arange(1, 11)
m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
mask = m1 < 6
mask

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [ ]:
m1[[ True,  True,  True,  True,  True, False, False, False, False,False]]

array([1, 2, 3, 4, 5])

In [ ]:
m1[mask]

array([1, 2, 3, 4, 5])

In [ ]:
m1[m1>6]

array([ 7,  8,  9, 10])

In [ ]:
# all even numbers....
m1%2==0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [ ]:
m1[m1%2==0]

array([ 2,  4,  6,  8, 10])

In [ ]:
m1[m1%2==1]

array([1, 3, 5, 7, 9])

In [ ]:
a = [1,2,3,4,5]
b = [8,7,6]
a[3:] = b[::-2]
a

[1, 2, 3, 6, 8]

In [ ]:
b[::-2]

[6, 8]

In [ ]:
# https://drive.google.com/file/d/1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK/view?usp=sharing

In [ ]:
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

Downloading...
From: https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
To: /content/survey.txt
100% 2.55k/2.55k [00:00<00:00, 9.66MB/s]


In [ ]:
scores = np.loadtxt('survey.txt', dtype='int')

In [ ]:
scores

array([ 7, 10,  5, ...,  5,  9, 10])

In [ ]:
type(scores)

numpy.ndarray

In [ ]:
scores.ndim

1

In [ ]:
scores.shape

(1167,)

In [ ]:
# NPS = %promotors - %detractors

In [ ]:
total = scores.shape[0]

1167

In [ ]:
nP = scores[scores>8].shape[0]
nD = scores[scores<7].shape[0]

In [ ]:
NPS = 100*(nP - nD)/total
NPS = round(NPS, 1)

In [ ]:
print(NPS)

23.7
